service: filesharing-backend
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-2

# functions:
#  hello:
#    handler: handler.hello

resources:
  Resources:
    FileBucket:
      Type: AWS::S3::Bucket
      DeletionPolicy: Retain
      Properties:
        BucketName: ${file(./file-sharing-bucket.cjs):bucketName}
        BucketEncryption:
          ServerSideEncryptionConfiguration:
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: AES256
        PublicAccessBlockConfiguration:
          BlockPublicAcls:  true
          BlockPublicPolicy:  true
          IgnorePublicAcls: true
          RestrictPublicBuckets:  true
        NotificationConfiguration:
          EventBridgeConfiguration: 
            EventBridgeEnabled: true
